### ISSUE TITLE
Where can I download "solver_unet.prototxt" and "phseg_v5.caffemodel" 

### ISSUE THREAD

**Issue by tianzq** [mohamed-ezz/saratan#1]
Where can I download these two files, which are used in "notebooks/realtime_train.ipynb"?
Thanks.

**Comment by mohamed-ezz** [comment]
I initially got them from the UNET author here : http://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/u-net-release-2015-10-02.tar.gz

Then I did some changes to the solver and network definition prototxt. I just pushed my changes here 7d7b9d9. Remember to modify the last convolutional layer according to the number of outputs you need (here I have 3 or 2 classes).

**Comment by mubo123** [comment]
I couldnt understand the strucre of your code. Fron which file we will start the program and step by step to get the results. The dataset you mentioned I downloaded this dataset but the formate of this dataset is totallly different from the 3DIRDb dataset. Please give a whole guidelines because its easy for me to get started .

**Comment by mohamed-ezz** [comment]
Hi @mubo123 , What are you trying to achieve?
Which dataset have you downloaded ? We mainly use 3D-IRCADb-01 dataset and FIRE3 dataset (which is not yet public).

Let me know in detail how I can help. I'll close this issue for now since it was meant for the prototxt files, you can create another issue for your questions.

**Comment by ksnzh** [comment]
@mohamed-ezz 3D-IRCADb-01 dataset does not have .nii format data.
When I run the irca_to_nii.py, an error occurred.
```
➜  3Dircadb1 python ../CFCN/saratan/data/irca_to_nii.py
Volume 3Dircadb1.1
	 Flipping left-right ./3Dircadb1.1/image1.nii to ./niftis_segmented_all/image01.nii
Traceback (most recent call last):
  File "../CFCN/saratan/data/irca_to_nii.py", line 86, in <module>
    flip_volume(image_filename, os.path.join(OUTPUT_PATH, "image%.2d"%int(volume_id)+".nii"))
  File "../CFCN/saratan/data/irca_to_nii.py", line 27, in flip_volume
    volume = nibabel.load(input_filename).get_data()
  File "/usr/local/lib/python2.7/dist-packages/nibabel/loadsave.py", line 40, in load
    raise FileNotFoundError("No such file: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file: './3Dircadb1.1/image1.nii'
```
